---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: devops-toolkit
  labels:
    app: devops-toolkit
    component: web
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
