---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: silly-demo
  labels:
    app.kubernetes.io/name: silly-demo
spec:
  replicas: 3
  selector:
    matchLabels:
      app: silly-demo
  template:
    metadata:
      labels:
        app: silly-demo
    spec:
      containers:
        - ports:
            - containerPort: 8080
          resources:
            limits:
              cpu: 500m
              memory: 512Mi
            requests:
              cpu: 250m
              memory: 256Mi
          name: silly-demo
          image: vfarcic/silly-demo:1.0.7
          livenessProbe:
            httpGet:
              path: /
              port: 8080
          readinessProbe:
            httpGet:
              path: /
              port: 8080
